# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f93da51f11a495a47e41a98952912f29adce39d839809ff82ac6ef846ea3ffa7bf1e7e6b2eba70c86ccca99c521029c8457175b655618352045e250f4802bba9

test:
  secret_key_base: 16356d341fe282785c9b33ede12c4223281479616d79073c8dd62becf4ea1b1ce7ed4f2ffbfbe697d16e5551accbca3a5ba89e61834f39c0cf804cae9276a451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
